# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import img
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1007, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 351, 61))
        self.groupBox.setObjectName("groupBox")
        self.txtPuerto = QtWidgets.QLineEdit(self.groupBox)
        self.txtPuerto.setGeometry(QtCore.QRect(10, 30, 241, 23))
        self.txtPuerto.setObjectName("txtPuerto")
        self.btnConectar = QtWidgets.QPushButton(self.groupBox)
        self.btnConectar.setGeometry(QtCore.QRect(260, 30, 80, 23))
        self.btnConectar.setObjectName("btnConectar")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(810, 10, 191, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnAdquirir = QtWidgets.QPushButton(self.groupBox_2)
        self.btnAdquirir.setGeometry(QtCore.QRect(10, 30, 80, 23))
        self.btnAdquirir.setObjectName("btnAdquirir")
        self.btnMotor = QtWidgets.QPushButton(self.groupBox_2)
        self.btnMotor.setGeometry(QtCore.QRect(100, 30, 80, 23))
        self.btnMotor.setObjectName("btnMotor")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 80, 991, 431))
        self.widget.setObjectName("widget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 520, 671, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioSobre = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioSobre.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.radioSobre.setChecked(True)
        self.radioSobre.setObjectName("radioSobre")
        self.radioSub = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioSub.setGeometry(QtCore.QRect(160, 30, 131, 21))
        self.radioSub.setObjectName("radioSub")
        self.txtWn = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtWn.setGeometry(QtCore.QRect(50, 60, 113, 23))
        self.txtWn.setObjectName("txtWn")
        self.txtZ = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtZ.setGeometry(QtCore.QRect(210, 60, 113, 23))
        self.txtZ.setObjectName("txtZ")
        self.txtAlpha = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtAlpha.setGeometry(QtCore.QRect(370, 60, 113, 23))
        self.txtAlpha.setObjectName("txtAlpha")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(20, 60, 21, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(190, 60, 21, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(350, 60, 21, 16))
        self.label_3.setObjectName("label_3")
        self.txtK = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtK.setGeometry(QtCore.QRect(540, 60, 113, 23))
        self.txtK.setObjectName("txtK")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(510, 60, 21, 16))
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(690, 520, 311, 101))
        self.frame.setStyleSheet("image: url(:/img/s1.PNG)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Adquision de datos"))
        self.groupBox.setTitle(_translate("MainWindow", "Conexión"))
        self.txtPuerto.setText(_translate("MainWindow", "/dev/ttyACM0"))
        self.btnConectar.setText(_translate("MainWindow", "Conectar"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Acciones"))
        self.btnAdquirir.setText(_translate("MainWindow", "Adquirir"))
        self.btnMotor.setText(_translate("MainWindow", "Motor: OFF"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Seleccion tipo de sistema"))
        self.radioSobre.setText(_translate("MainWindow", "Sobreamortiguado"))
        self.radioSub.setText(_translate("MainWindow", "Subamortiguado"))
        self.label.setText(_translate("MainWindow", "Wn"))
        self.label_2.setText(_translate("MainWindow", "ζ"))
        self.label_3.setText(_translate("MainWindow", "α"))
        self.label_4.setText(_translate("MainWindow", "K"))

